### ISSUE TITLE
Too much paid resources 

### ISSUE THREAD

**Issue by yaserrahimi** [DjangoEx/python-backend-roadmap#24]
If we have some more free and open source resources make better roadmap to this community!

**Comment by bobycloud** [comment]
Hi,
Just books are paid resources. If you don't know how to access them join https://t.me/djangoir and ask. It's not an issue.
Best regards

**Comment by yaserrahimi** [comment]
I can't join to that maybe someone blocked me

**Comment by bobycloud** [comment]
Please send a message to my telegram account: https://t.me/bobycloud

**Comment by yaserrahimi** [comment]
I can't do that too
Add me yourself
@yasercode
